"HandOverAboutTalents1" = G3ActionTemplate {
	ActionName = "HandOverAboutTalents1";
	IconName = "AboutTalents1";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.AboutTalents1.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"AboutTalents1"};
		},
	};
};

"HandOverAboutTalents2" = G3ActionTemplate {
	ActionName = "HandOverAboutTalents2";
	IconName = "AboutTalents2";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.AboutTalents2.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"AboutTalents2"};
		},
	};
};

"HandOverAlmanac" = G3ActionTemplate {
	ActionName = "HandOverAlmanac";
	IconName = "Almanac";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Almanac.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Almanac"};
		},
	};
};

"HandOverAntidote" = G3ActionTemplate {
	ActionName = "HandOverAntidote";
	IconName = "Antidote";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Antidote.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Antidote"};
		},
	};
};

"HandOverArgusEyeglasses" = G3ActionTemplate {
	ActionName = "HandOverArgusEyeglasses";
	IconName = "ArgusEyeglasses";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ArgusEyeglasses.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ArgusEyeglasses"};
		},
	};
};

"HandOverAxe" = G3ActionTemplate {
	ActionName = "HandOverAxe";
	IconName = "Axe";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Axe.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Axe"};
		},
	};
};

"HandOverBackpack" = G3ActionTemplate {
	ActionName = "HandOverBackpack";
	IconName = "Backpack";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Backpack.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Backpack"};
		},
	};
};

"HandOverBandage" = G3ActionTemplate {
	ActionName = "HandOverBandage";
	IconName = "Bandage";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Bandage.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Bandage"};
		},
	};
};

"HandOverBarrelBrewerBeer" = G3ActionTemplate {
	ActionName = "HandOverBarrelBrewerBeer";
	IconName = "BarrelBrewerBeer";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.BarrelBrewerBeer.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"BarrelBrewerBeer"};
		},
	};
};

"HandOverBeltOfMetaphysics" = G3ActionTemplate {
	ActionName = "HandOverBeltOfMetaphysics";
	IconName = "BeltOfMetaphysics";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.BeltOfMetaphysics.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"BeltOfMetaphysics"};
		},
	};
};

"HandOverBetrayedCaptain" = G3ActionTemplate {
	ActionName = "HandOverBetrayedCaptain";
	IconName = "BetrayedCaptain";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.BetrayedCaptain.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"BetrayedCaptain"};
		},
	};
};

"HandOverBlackWidowPoison" = G3ActionTemplate {
	ActionName = "HandOverBlackWidowPoison";
	IconName = "BlackWidowPoison";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.BlackWidowPoison.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"BlackWidowPoison"};
		},
	};
};

"HandOverBlanket" = G3ActionTemplate {
	ActionName = "HandOverBlanket";
	IconName = "Blanket";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Blanket.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Blanket"};
		},
	};
};

"HandOverBomb" = G3ActionTemplate {
	ActionName = "HandOverBomb";
	IconName = "Bomb";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Bomb.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Bomb"};
		},
	};
};

"HandOverBoneBracelet" = G3ActionTemplate {
	ActionName = "HandOverBoneBracelet";
	IconName = "BoneBracelet";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.BoneBracelet.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"BoneBracelet"};
		},
	};
};

"HandOverBoneTalisman" = G3ActionTemplate {
	ActionName = "HandOverBoneTalisman";
	IconName = "BoneTalisman";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.BoneTalisman.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"BoneTalisman"};
		},
	};
};

"HandOverBoozyBreathBeer" = G3ActionTemplate {
	ActionName = "HandOverBoozyBreathBeer";
	IconName = "BoozyBreathBeer";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.BoozyBreathBeer.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"BoozyBreathBeer"};
		},
	};
};

"HandOverCake" = G3ActionTemplate {
	ActionName = "HandOverCake";
	IconName = "Cake";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Cake.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Cake"};
		},
	};
};

"HandOverCart" = G3ActionTemplate {
	ActionName = "HandOverCart";
	IconName = "LeatherCart";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Cart.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Cart"};
		},
	};
};

"HandOverCartBig" = G3ActionTemplate {
	ActionName = "HandOverCartBig";
	IconName = "LeatherCartBig";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.CartBig.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"CartBig"};
		},
	};
};

"HandOverChainmail" = G3ActionTemplate {
	ActionName = "HandOverChainmail";
	IconName = "Chainmail";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Chainmail.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Chainmail"};
		},
	};
};

"HandOverCider" = G3ActionTemplate {
	ActionName = "HandOverCider";
	IconName = "Cider";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Cider.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Cider"};
		},
	};
};

"HandOverComb" = G3ActionTemplate {
	ActionName = "HandOverComb";
	IconName = "Comb";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Comb.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Comb"};
		},
	};
};

"HandOverConstructionPlan" = G3ActionTemplate {
	ActionName = "HandOverConstructionPlan";
	IconName = "ConstructionPlan";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ConstructionPlan.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ConstructionPlan"};
		},
	};
};

"HandOverCopperBracelet" = G3ActionTemplate {
	ActionName = "HandOverCopperBracelet";
	IconName = "CopperBracelet";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.CopperBracelet.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"CopperBracelet"};
		},
	};
};

"HandOverCreamPie" = G3ActionTemplate {
	ActionName = "HandOverCreamPie";
	IconName = "CreamPie";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.CreamPie.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"CreamPie"};
		},
	};
};

"HandOverCrossbow" = G3ActionTemplate {
	ActionName = "HandOverCrossbow";
	IconName = "Crossbow";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Crossbow.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Crossbow"};
		},
	};
};

"HandOverDagger" = G3ActionTemplate {
	ActionName = "HandOverDagger";
	IconName = "Dagger";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Dagger.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Dagger"};
		},
	};
};

"HandOverDarkTalisman" = G3ActionTemplate {
	ActionName = "HandOverDarkTalisman";
	IconName = "DarkTalisman";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.DarkTalisman.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"DarkTalisman"};
		},
	};
};

"HandOverDartagnansFragrance" = G3ActionTemplate {
	ActionName = "HandOverDartagnansFragrance";
	IconName = "DartagnansFragrance";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.DartagnansFragrance.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"DartagnansFragrance"};
		},
	};
};

"HandOverDiamond" = G3ActionTemplate {
	ActionName = "HandOverDiamond";
	IconName = "Diamond";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Diamond.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Diamond"};
		},
	};
};

"HandOverDiamondStaff" = G3ActionTemplate {
	ActionName = "HandOverDiamondStaff";
	IconName = "DiamondStaff";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.DiamondStaff.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"DiamondStaff"};
		},
	};
};

"HandOverDogCompanion" = G3ActionTemplate {
	ActionName = "HandOverDogCompanion";
	IconName = "DogCompanion";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.DogCompanion.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"DogCompanion"};
		},
	};
};

"HandOverDrFaustusElixir" = G3ActionTemplate {
	ActionName = "HandOverDrFaustusElixir";
	IconName = "DrFaustusElixir";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.DrFaustusElixir.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"DrFaustusElixir"};
		},
	};
};

"HandOverDrunkardBrewBeer" = G3ActionTemplate {
	ActionName = "HandOverDrunkardBrewBeer";
	IconName = "DrunkardBrewBeer";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.DrunkardBrewBeer.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"DrunkardBrewBeer"};
		},
	};
};

"HandOverElegantRapier" = G3ActionTemplate {
	ActionName = "HandOverElegantRapier";
	IconName = "ElegantRapier";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ElegantRapier.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ElegantRapier"};
		},
	};
};

"HandOverEndurenceDrink" = G3ActionTemplate {
	ActionName = "HandOverEndurenceDrink";
	IconName = "EndurenceDrink";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.EndurenceDrink.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"EndurenceDrink"};
		},
	};
};

"HandOverFlowerOfDiscord" = G3ActionTemplate {
	ActionName = "HandOverFlowerOfDiscord";
	IconName = "FlowerOfDiscord";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.FlowerOfDiscord.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"FlowerOfDiscord"};
		},
	};
};

"HandOverFortuneCake" = G3ActionTemplate {
	ActionName = "HandOverFortuneCake";
	IconName = "FortuneCake";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.FortuneCake.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"FortuneCake"};
		},
	};
};

"HandOverGambeson" = G3ActionTemplate {
	ActionName = "HandOverGambeson";
	IconName = "Gambeson";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Gambeson.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Gambeson"};
		},
	};
};

"HandOverGemRing" = G3ActionTemplate {
	ActionName = "HandOverGemRing";
	IconName = "GemRing";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.GemRing.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"GemRing"};
		},
	};
};

"HandOverGhostlyFog" = G3ActionTemplate {
	ActionName = "HandOverGhostlyFog";
	IconName = "GhostlyFog";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.GhostlyFog.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"GhostlyFog"};
		},
	};
};

"HandOverGoldChain" = G3ActionTemplate {
	ActionName = "HandOverGoldChain";
	IconName = "GoldChain";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.GoldChain.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"GoldChain"};
		},
	};
};

"HandOverGrindstone" = G3ActionTemplate {
	ActionName = "HandOverGrindstone";
	IconName = "Grindstone";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Grindstone.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Grindstone"};
		},
	};
};

"HandOverHerbTea" = G3ActionTemplate {
	ActionName = "HandOverHerbTea";
	IconName = "HerbTea";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.HerbTea.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"HerbTea"};
		},
	};
};

"HandOverIronBracelet" = G3ActionTemplate {
	ActionName = "HandOverIronBracelet";
	IconName = "IronBracelet";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.IronBracelet.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"IronBracelet"};
		},
	};
};

"HandOverJuice" = G3ActionTemplate {
	ActionName = "HandOverJuice";
	IconName = "Juice";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Juice.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Juice"};
		},
	};
};

"HandOverLeatherArmor" = G3ActionTemplate {
	ActionName = "HandOverLeatherArmor";
	IconName = "LeatherArmor";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.LeatherArmor.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"LeatherArmor"};
		},
	};
};

"HandOverLeatherGloves" = G3ActionTemplate {
	ActionName = "HandOverLeatherGloves";
	IconName = "LeatherGloves";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.LeatherGloves.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"LeatherGloves"};
		},
	};
};

"HandOverLockPicks" = G3ActionTemplate {
	ActionName = "HandOverLockPicks";
	IconName = "LockPicks";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.LockPicks.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"LockPicks"};
		},
	};
};

"HandOverLongsword" = G3ActionTemplate {
	ActionName = "HandOverLongsword";
	IconName = "Longsword";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Longsword.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Longsword"};
		},
	};
};

"HandOverLuckyStone" = G3ActionTemplate {
	ActionName = "HandOverLuckyStone";
	IconName = "LuckyStone";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.LuckyStone.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"LuckyStone"};
		},
	};
};

"HandOverMace" = G3ActionTemplate {
	ActionName = "HandOverMace";
	IconName = "Mace";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Mace.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Mace"};
		},
	};
};

"HandOverMead" = G3ActionTemplate {
	ActionName = "HandOverMead";
	IconName = "Mead";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Mead.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Mead"};
		},
	};
};

"HandOverMedalOfHonor" = G3ActionTemplate {
	ActionName = "HandOverMedalOfHonor";
	IconName = "MedalOfHonor";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.MedalOfHonor.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"MedalOfHonor"};
		},
	};
};

"HandOverMetalHammer" = G3ActionTemplate {
	ActionName = "HandOverMetalHammer";
	IconName = "MetalHammer";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.MetalHammer.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"MetalHammer"};
		},
	};
};

"HandOverMoneyBag" = G3ActionTemplate {
	ActionName = "HandOverMoneyBag";
	IconName = "MoneyBag";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.MoneyBag.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"MoneyBag"};
		},
	};
};

"HandOverMuralPainting" = G3ActionTemplate {
	ActionName = "HandOverMuralPainting";
	IconName = "MuralPainting";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.MuralPainting.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"MuralPainting"};
		},
	};
};

"HandOverNightcap" = G3ActionTemplate {
	ActionName = "HandOverNightcap";
	IconName = "Nightcap";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Nightcap.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Nightcap"};
		},
	};
};

"HandOverOakwoodRing" = G3ActionTemplate {
	ActionName = "HandOverOakwoodRing";
	IconName = "OakwoodRing";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.OakwoodRing.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"OakwoodRing"};
		},
	};
};

"HandOverPainKiller" = G3ActionTemplate {
	ActionName = "HandOverPainKiller";
	IconName = "PainKiller";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.PainKiller.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"PainKiller"};
		},
	};
};

"HandOverParalysisPoison" = G3ActionTemplate {
	ActionName = "HandOverParalysisPoison";
	IconName = "ParalysisPoison";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ParalysisPoison.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ParalysisPoison"};
		},
	};
};

"HandOverPerfume" = G3ActionTemplate {
	ActionName = "HandOverPerfume";
	IconName = "Perfume";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Perfume.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Perfume"};
		},
	};
};

"HandOverPestAway" = G3ActionTemplate {
	ActionName = "HandOverPestAway";
	IconName = "PestAway";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.PestAway.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"PestAway"};
		},
	};
};

"HandOverPistol" = G3ActionTemplate {
	ActionName = "HandOverPistol";
	IconName = "Pistol";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Pistol.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Pistol"};
		},
	};
};

"HandOverPlatemail" = G3ActionTemplate {
	ActionName = "HandOverPlatemail";
	IconName = "Platemail";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Platemail.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Platemail"};
		},
	};
};

"HandOverPoem" = G3ActionTemplate {
	ActionName = "HandOverPoem";
	IconName = "Poem";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Poem.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Poem"};
		},
	};
};

"HandOverPoisonDagger" = G3ActionTemplate {
	ActionName = "HandOverPoisonDagger";
	IconName = "PoisonDagger";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.PoisonDagger.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"PoisonDagger"};
		},
	};
};

"HandOverPoisonTrap" = G3ActionTemplate {
	ActionName = "HandOverPoisonTrap";
	IconName = "PoisonTrap";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.PoisonTrap.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"PoisonTrap"};
		},
	};
};

"HandOverPowderOfHygeia" = G3ActionTemplate {
	ActionName = "HandOverPowderOfHygeia";
	IconName = "PowderOfHygeia";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.PowderOfHygeia.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"PowderOfHygeia"};
		},
	};
};

"HandOverRapier" = G3ActionTemplate {
	ActionName = "HandOverRapier";
	IconName = "Rapier";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Rapier.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Rapier"};
		},
	};
};

"HandOverRoseWater" = G3ActionTemplate {
	ActionName = "HandOverRoseWater";
	IconName = "RoseWater";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.RoseWater.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"RoseWater"};
		},
	};
};

"HandOverRubinStaff" = G3ActionTemplate {
	ActionName = "HandOverRubinStaff";
	IconName = "RubinStaff";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.RubinStaff.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"RubinStaff"};
		},
	};
};

"HandOverShadowDagger" = G3ActionTemplate {
	ActionName = "HandOverShadowDagger";
	IconName = "ShadowDagger";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ShadowDagger.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ShadowDagger"};
		},
	};
};

"HandOverShield" = G3ActionTemplate {
	ActionName = "HandOverShield";
	IconName = "Shield";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Shield.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Shield"};
		},
	};
};

"HandOverShortSword" = G3ActionTemplate {
	ActionName = "HandOverShortSword";
	IconName = "ShortSword";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ShortSword.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ShortSword"};
		},
	};
};

"HandOverSignetGuildofCraftsmen" = G3ActionTemplate {
	ActionName = "HandOverSignetGuildofCraftsmen";
	IconName = "SignetGuildofCraftsmen";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SignetGuildofCraftsmen.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SignetGuildofCraftsmen"};
		},
	};
};

"HandOverSignetGuildofMerchants" = G3ActionTemplate {
	ActionName = "HandOverSignetGuildofMerchants";
	IconName = "SignetGuildofMerchants";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SignetGuildofMerchants.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SignetGuildofMerchants"};
		},
	};
};

"HandOverSilverChain" = G3ActionTemplate {
	ActionName = "HandOverSilverChain";
	IconName = "SilverChain";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SilverChain.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SilverChain"};
		},
	};
};

"HandOverSilverRing" = G3ActionTemplate {
	ActionName = "HandOverSilverRing";
	IconName = "SilverRing";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SilverRing.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SilverRing"};
		},
	};
};

"HandOverSkullLamp" = G3ActionTemplate {
	ActionName = "HandOverSkullLamp";
	IconName = "SkullLamp";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SkullLamp.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SkullLamp"};
		},
	};
};

"HandOverSlateBoard" = G3ActionTemplate {
	ActionName = "HandOverSlateBoard";
	IconName = "SlateBoard";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SlateBoard.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SlateBoard"};
		},
	};
};

"HandOverSlateTile" = G3ActionTemplate {
	ActionName = "HandOverSlateTile";
	IconName = "SlateTile";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SlateTile.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SlateTile"};
		},
	};
};

"HandOverSmallBeer" = G3ActionTemplate {
	ActionName = "HandOverSmallBeer";
	IconName = "SmallBeer";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SmallBeer.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SmallBeer"};
		},
	};
};

"HandOverSpinningTop" = G3ActionTemplate {
	ActionName = "HandOverSpinningTop";
	IconName = "SpinningTop";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.SpinningTop.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"SpinningTop"};
		},
	};
};

"HandOverStatelyDispatch" = G3ActionTemplate {
	ActionName = "HandOverStatelyDispatch";
	IconName = "StatelyDispatch";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.StatelyDispatch.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"StatelyDispatch"};
		},
	};
};

"HandOverStinkBomb" = G3ActionTemplate {
	ActionName = "HandOverStinkBomb";
	IconName = "StinkBomb";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.StinkBomb.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"StinkBomb"};
		},
	};
};

"HandOverStoneSoldier" = G3ActionTemplate {
	ActionName = "HandOverStoneSoldier";
	IconName = "StoneSoldier";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.StoneSoldier.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"StoneSoldier"};
		},
	};
};

"HandOverStrongDoorLatch" = G3ActionTemplate {
	ActionName = "HandOverStrongDoorLatch";
	IconName = "StrongDoorLatch";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.StrongDoorLatch.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"StrongDoorLatch"};
		},
	};
};

"HandOverTalismanOfInspiration" = G3ActionTemplate {
	ActionName = "HandOverTalismanOfInspiration";
	IconName = "TalismanOfInspiration";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.TalismanOfInspiration.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"TalismanOfInspiration"};
		},
	};
};

"HandOverThrowingKnife" = G3ActionTemplate {
	ActionName = "HandOverThrowingKnife";
	IconName = "ThrowingKnife";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ThrowingKnife.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ThrowingKnife"};
		},
	};
};

"HandOverToadExcrements" = G3ActionTemplate {
	ActionName = "HandOverToadExcrements";
	IconName = "ToadExcrements";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ToadExcrements.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ToadExcrements"};
		},
	};
};

"HandOverToadSlime" = G3ActionTemplate {
	ActionName = "HandOverToadSlime";
	IconName = "ToadSlime";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.ToadSlime.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"ToadSlime"};
		},
	};
};

"HandOverTorch" = G3ActionTemplate {
	ActionName = "HandOverTorch";
	IconName = "Torch";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.Torch.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"Torch"};
		},
	};
};

"HandOverWalkingStick" = G3ActionTemplate {
	ActionName = "HandOverWalkingStick";
	IconName = "WalkingStick";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.WalkingStick.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"WalkingStick"};
		},
	};
};

"HandOverWarBanner" = G3ActionTemplate {
	ActionName = "HandOverWarBanner";
	IconName = "WarBanner";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.WarBanner.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"WarBanner"};
		},
	};
};

"HandOverWeaponPoison" = G3ActionTemplate {
	ActionName = "HandOverWeaponPoison";
	IconName = "WeaponPoison";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.WeaponPoison.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"WeaponPoison"};
		},
	};
};

"HandOverWheatBeer" = G3ActionTemplate {
	ActionName = "HandOverWheatBeer";
	IconName = "WheatBeer";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.WheatBeer.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"WheatBeer"};
		},
	};
};

"HandOverWheatBread" = G3ActionTemplate {
	ActionName = "HandOverWheatBread";
	IconName = "WheatBread";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.WheatBread.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"WheatBread"};
		},
	};
};

"HandOverWoodenShield" = G3ActionTemplate {
	ActionName = "HandOverWoodenShield";
	IconName = "WoodenShield";

@base/HandOverItem

	SuccessResult = array {
		FunctionTransferItems
		{
			Filter = "Source.hasItems.WoodenShield.1";
			Giver = "Source";
			Receiver = "Target";
			MinAmount = 1;
			MaxAmount = 1;
			SpecificItems = array{"WoodenShield"};
		},
	};
};